# Generated by Django 5.2.6 on 2025-10-03 10:28

import django.db.models.deletion
from django.db import migrations, models
from django_jsonform.models.fields import JSONField

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                (
                    "discount_percentage",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("short_description", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "specification",
                    JSONField(blank=True, default=dict, null=True),
                ),
                ("shipping_cost", models.PositiveSmallIntegerField()),
                ("quantity", models.PositiveIntegerField(db_default=0, default=0)),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        db_default=0, default=0, editable=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="apps.category",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="apps.tag")),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="apps.product",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_percentage__gte", 0), ("discount_percentage__lte", 100)
                ),
                name="discount_percentage_gte_0_lte_110",
            ),
        ),
    ]
