# Generated by Django 5.2.6 on 2025-10-03 10:37

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="discount_percentage_gte_0_lte_110",
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_percentage",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                help_text="Discount percentage must be between 0 and 100",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="specification",
            field=django_jsonform.models.fields.JSONField(blank=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_percentage__gte", 0), ("discount_percentage__lte", 100)
                ),
                name="discount_percentage_gte_0_lte_100",
                violation_error_message="Discount percentage must be between 0 and 100",
            ),
        ),
    ]
